<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MacBook-Pro" failures="3" tests="3" name="invalidPost" time="0.42" errors="0" timestamp="2023-08-17T17:00:28 SGT">
  <testcase classname="lab8_Example.Test_invalidPost" name="TC08_StatusCodeChecked" time="0.003">
    <failure type="java.lang.AssertionError" message="Status check Failed! expected [400] but found [201]">
      <![CDATA[java.lang.AssertionError: Status check Failed! expected [400] but found [201]
at lab8_Example.Test_invalidPost.TC08_StatusCodeChecked(Test_invalidPost.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TC08_StatusCodeChecked -->
  <testcase classname="lab8_Example.Test_invalidPost" name="TC09_MessageFieldChecked" time="0.001">
    <failure type="java.lang.AssertionError" message="Message field check Failed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Message field check Failed! expected [true] but found [false]
at lab8_Example.Test_invalidPost.TC09_MessageFieldChecked(Test_invalidPost.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC09_MessageFieldChecked -->
  <testcase classname="lab8_Example.Test_invalidPost" name="TC10_VerifyOnMessageContainName" time="0.015">
    <failure type="java.lang.AssertionError" message="Message does not contain invalid field! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Message does not contain invalid field! expected [true] but found [false]
at lab8_Example.Test_invalidPost.TC10_VerifyOnMessageContainName(Test_invalidPost.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC10_VerifyOnMessageContainName -->
</testsuite> <!-- invalidPost -->
