<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MacBook-Pro" failures="3" tests="3" name="invalidBody" time="0.489" errors="0" timestamp="2023-08-16T15:21:41 SGT">
  <testcase classname="Lab8.Lab8_Example.Test_invalidBody" name="TC08_StatusCodeChecked" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [400] but found [201]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [201]
at Lab8.Lab8_Example.Test_invalidBody.TC08_StatusCodeChecked(Test_invalidBody.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC08_StatusCodeChecked -->
  <testcase classname="Lab8.Lab8_Example.Test_invalidBody" name="TC09_MessageFieldChecked" time="0.002">
    <failure type="java.lang.AssertionError" message="Message field check Failed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Message field check Failed! expected [true] but found [false]
at Lab8.Lab8_Example.Test_invalidBody.TC09_MessageFieldChecked(Test_invalidBody.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC09_MessageFieldChecked -->
  <testcase classname="Lab8.Lab8_Example.Test_invalidBody" name="TC10_VerifyOnMessageContainName" time="0.014">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;String.contains(java.lang.CharSequence)&amp;quot; because &amp;quot;resName&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "resName" is null
at Lab8.Lab8_Example.Test_invalidBody.TC10_VerifyOnMessageContainName(Test_invalidBody.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- TC10_VerifyOnMessageContainName -->
</testsuite> <!-- invalidBody -->
